FROM node:18-alpine AS base
WORKDIR /app

# Install dependencies only once
COPY package*.json ./
RUN npm install --only=production
COPY . .

# Development stage
FROM base AS development
ENV NODE_ENV=development
RUN npm install --only=development
CMD ["npm", "run", "dev"]

# Production stage
FROM base AS production
ENV NODE_ENV=production
CMD ["npm", "run", "start"]

EXPOSE 4000